Fix compile error for clang update.
system/teeui/libteeui/example/teeui.cpp:130:9: error:
call to member function 'setParam' is ambiguous
    ctx.setParam<RightEdgeOfScreen>(pxs(sDeviceInfo.width_));
    ~~~~^~~~~~~~~~~~~~~~~~~~~~~~~~~
system/teeui/libteeui/include/teeui/utils.h:468:10: note: candidate function
[with MetaParam = teeui::MetaParam<teeui::Param_RightEdgeOfScreen,
 teeui::Coordinate<teeui::UnitT<teeui::Unit::PX>, float> >]
    void setParam(
         ^
system/teeui/libteeui/include/teeui/utils.h:475:10: note: candidate function
[with MetaParam = teeui::MetaParam<teeui::Param_RightEdgeOfScreen,
teeui::Coordinate<teeui::UnitT<teeui::Unit::PX>, float> >,
Unit = teeui::UnitT<teeui::Unit::PX>, N = float, $3 = void]
    void setParam(const Coordinate<Unit, N>& v) {
         ^

Bug: 149839606
Test: build.
Change-Id: I85972a6f042933540a371686e1a1d2bf422519af
Merged-In: I85972a6f042933540a371686e1a1d2bf422519af
(cherry picked from commit 0d0d97559b7072c487ff7e8a82fb32587c381672)